app = "fanggo"
primary_region = "sin"

# 🔥 云端编译，不报错，支持 sqlite3
[build]
  builder = "paketobuildpacks/builder:base"

# 家目录 ~ → /data（永久保存数据库）
[env]
  HOME = "/data"

[[mounts]]
  source = "data"
  destination = "/data"

# 启动命令：./app start（你要的参数）
[processes]
  app = "./app start"

# 公网访问
[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
